### ISSUE TITLE
Seems to be broken on Openhab 3.3

### ISSUE THREAD

**Issue by ThaDaVos** [sichelz1/sonos-coordinator#10]
It seems the latest 3.3 release has broken this automation script as the `addItem` signature has changed and takes an object now instead of separate parameters:

![image](https://user-images.githubusercontent.com/5251028/181903576-38681864-5d1e-473d-8162-486d941b800a.png)

I'll create a PR with this change for you

**Comment by sichelz1** [comment]
I have merged your pr into the master so i'm going to close this issue. Thank you again for your contribution.

**Comment by ThaDaVos** [comment]
You're welcome - I noticed it was broken after I temporarily removed all automation scrips as I was having other problems - so it of course removed the items too
