### ISSUE TITLE
mute not working

### ISSUE THREAD

**Issue by stamateviorel** [sichelz1/sonos-coordinator#3]
Maybe i am doing something wrong i have only one sonos thing and cannot mute this are the logs

`└2022-02-10 14:25:17.745 [INFO ] [openhab.event.ItemCommandEvent      ] - Item 'RINCON_542A1BEE635801400_ZoneMute_SonosProxyItem' received command ON                                                                                                                         │─2022-02-10 14:25:17.746 [INFO ] [org.openhab.automation.script       ] - Rule zone mute item RINCON_542A1BEE635801400_ZoneMute_SonosProxyItem received command started!                                                                                                      │─2022-02-10 14:25:17.746 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'RINCON_542A1BEE635801400_ZoneMute_SonosProxyItem' changed from OFF to ON                                                                                                                      │─2022-02-10 14:25:17.747 [INFO ] [org.openhab.automation.script       ] - Setting mute state to ON of all grouped sonos players of from zone coordinator Wash Area   `

but the mute item doesn't get updated

**Comment by stamateviorel** [comment]
No from the widget speaker icon cannot mute/unmute the player and also it doesn't update state from the player to the icon in the widget. The mute item is linked to the channel so i can control the proxy item created by the rule and it works as expected.

**Comment by sichelz1** [comment]
I've never had a message like this whilst developing the script. I will try to do some tests on my system. For the meantime, does it work if you create the required sonos items(player, mute, volume etc. except the zone controller items) manually in the ui?

**Comment by sichelz1** [comment]
Did the other items like player artist album and cover art work?

**Comment by stamateviorel** [comment]
Hello again so now i am testing with 10 devices using your latest automation and widget. Openhab 3.2 on debian clean install added the things from ui then the rule everything ok but the channels dont get link to the items. Then i tried to add for one device and start the rule i get 
`[ERROR] [ipt.internal.ScriptEngineManagerImpl] - Error during evaluation of script 'file:/etc/openhab/automation/js/sonos_coordinator_rule.js': java.lang.IllegalArgumentException: Cannot add element, because an element with same UID `
So i dont understand what is happening with the channel linking i dont have any text based items everything trough the ui

**Comment by stamateviorel** [comment]
> Hello again so now i am testing with 10 devices using your latest automation and widget. Openhab 3.2 on debian clean install added the things from ui then the rule everything ok but the channels dont get link to the items. Then i tried to add for one device and start the rule i get `[ERROR] [ipt.internal.ScriptEngineManagerImpl] - Error during evaluation of script 'file:/etc/openhab/automation/js/sonos_coordinator_rule.js': java.lang.IllegalArgumentException: Cannot add element, because an element with same UID ` So i dont understand what is happening with the channel linking i dont have any text based items everything trough the ui

Ok small update. I only added one speaker then run the rule no linking of items ok so i link them manually no problem then i remove the script items are removed but when i add the script then the items are created and linked directly ??? so basically if the items were never linked manually the script doesn't know to what thing to link them

**Comment by sichelz1** [comment]
> so basically if the items were never linked manually the script doesn't know to what thing to link them
No, the rule works like the following: iterate over all things -> for all things, check the required channels if an item is bound to it. If yes, take the item, if not, create an item and link it to the channel.
As i created all my items manually, maybe there is a bug in the automatic creation of the items. This might also lead to your exception from above. The error basically says, that the script was unable to find a matching thing for the mute item, that had changed.
I recommend trying the following. Delete the rule, add the thing and all required items manually so that the rule does not need to create them. Then add the rule and see if this works.
I will look into this issue again next week, but as i'm about to have some days of, i think i will be able to check the issue not before wednesday next week

**Comment by stamateviorel** [comment]
After doing what you described mute gives an error in the logs but works the volume is not working then the grouping is working but not the ungrouping and the volume group doesn't show anything so i dont know.  Thank you and enjoy your time.

**Comment by sichelz1** [comment]
Alright, next round. I suspect your problem was because the master channel is not set, when your sonos devices have never been grouped/ungrouped and the rule relied on the channel. I've changed it so that the rule can cope with this situation.
If you should have any futher problems, it would be helpful for me to have a more complete excerpt from the log and the state of the SonosCoordinatorProxyItem would also be very helpful.

**Comment by sichelz1** [comment]
I found another error. You were right. The created items were never linked to any of the channels. I've encountered the issue while implemeting the favorites functionality. The latest script now links all created items with the correct channel of the thing

**Comment by stamateviorel** [comment]
Ok testing again. this are my findings when i start with virgin openhab everything ok items are created and linked for one player then i am like ok I add another player so i remove the script then i put it back then the problem is that it creates the first 2 items but it starts complaining that the last item is with the same uui that the script itself created in the first place. Even if manually remove it and start the script again same thing it makes 2 items and the last one it created it complains that the item already exist and even clearing cache openhab doesnt help i also look in the items nothing is there ...

**Comment by stamateviorel** [comment]
Doing more testing skipping the script creating stuff by itself i added all the items myself. Now from what i can test all working mute volume etc but grouping is strange so basically if i group in sonos app all the speakers in your widget i get one separate and all the others together so that means the single one in the widget is the master ? and the rest are slaves ?

**Comment by sichelz1** [comment]
> Ok testing again. this are my findings when i start with virgin openhab everything ok items are created and linked for one player then i am like ok I add another player so i remove the script then i put it back then the problem is that it creates the first 2 items but it starts complaining that the last item is with the same uui that the script itself created in the first place. Even if manually remove it and start the script again same thing it makes 2 items and the last one it created it complains that the item already exist and even clearing cache openhab doesnt help i also look in the items nothing is there ...
this is the output

I found the error. Apperently, the created channel links do not get implicitly deleted when the item is deleted. Therefore, when creating the item the next time, the previously created channel link is still present. I now remove all channel links of a created item before deleting the item. This should fix your problem and you should now be able to run it without creating any item by yourself

**Comment by sichelz1** [comment]
> Doing more testing skipping the script creating stuff by itself i added all the items myself. Now from what i can test all working mute volume etc but grouping is strange so basically if i group in sonos app all the speakers in your widget i get one separate and all the others together so that means the single one in the widget is the master ? and the rest are slaves ?
Well after more testing i discovered that all the players have to be in stopped position then if i choose one player and start it and then group all the rest i get only one grouped widget.

I just tested this scenario with my devices (i have three of them currently running). I ungrouped everything and started playing a radio stream on one device. Then i took the device and grouped the other 2 into it. This worked as well as ungrouping them.
Maybe this was a follow up error on your previouse errors?

**Comment by stamateviorel** [comment]
> I just tested this scenario with my devices (i have three of them currently running). I ungrouped everything and started playing a radio stream on one device. Then i took the device and grouped the other 2 into it. This worked as well as ungrouping them.
Maybe this was a follow up error on your previouse errors?

yes related to the previous error

**Comment by stamateviorel** [comment]
> I found the error. Apparently, the created channel links do not get implicitly deleted when the item is deleted. Therefore, when creating the item the next time, the previously created channel link is still present. I now remove all channel links of a created item before deleting the item. This should fix your problem and you should now be able to run it without creating any item by yourself

Great job everything working even with existing file based item and thing. Also without anything configured just added the things and the script created every item and linked it.

**Comment by sichelz1** [comment]
Great, i'm happy to hear that. Thanks for doing all the testing. Appreciate it.
