### ISSUE TITLE
5.1 Setup shows as 4 separate locations

### ISSUE THREAD

**Issue by Frenkii** [sichelz1/sonos-coordinator#8]
Hi, 
just a short question. My setup in the living room is Playbar, 2x one and Sub.
When I load the widget it shows like this:

![grafik](https://user-images.githubusercontent.com/20613151/180655492-f4e9145f-d96e-4c38-a351-0978b93147a2.png)

Models like this.
![grafik](https://user-images.githubusercontent.com/20613151/180655504-558dfdd7-14f6-477e-8a01-000585bac7ca.png)

What I am doing wrong?

Thank you in advance

**Comment by Frenkii** [comment]
Wow, thanks for the fast reply.
At least it shows only 1 Device (Group) here:
![grafik](https://user-images.githubusercontent.com/20613151/180780492-3fc76395-8662-4b22-8e87-38cc7fec2af4.png)

It still shows all volume bars. But I guess thats a Sonos thing:
![grafik](https://user-images.githubusercontent.com/20613151/180780633-4025913d-0700-45df-93ab-344246c5dde5.png)

**Comment by sichelz1** [comment]
You're welcome :-)
Yes, this is a bit more tricky. Normally, these are all your grouped speakers where you can control the volumes individually.
In your case, these are your channels (e.g. when you want to raise only the front left channel, it's one of those controls).
The main volume slider on the widget controls the whole volume of the group (they will be increased/decreased equally by the delta of the slider). It would not make sense to filter them out.
I think you now have two options: 
1. Rename your individual items with a matching item name (e.g. Hinten Links, Hinten Rechts Vorne Center, Subwoofer...) so you will have speaking names for your individual controls.  This however will then again display "Vorne Links + Vorne Rechts + Subwoofer + ..." in the main view.
2. Leave your configuration as is when you are not interested in changing your channel volumes individually.

**Comment by Frenkii** [comment]
Thank you for the detailed answer.
Great plugin ;)
